changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
    authors:
      - dependabot
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement
        - feat
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance & Refactoring
      labels:
        - refactor
        - refactoring
        - maintenance
        - chore
    - title: 🧪 Tests
      labels:
        - test
        - tests
        - testing
    - title: ⚡ Performance
      labels:
        - performance
        - perf
    - title: 🔒 Security
      labels:
        - security
    - title: 🎨 Style & Formatting
      labels:
        - style
        - formatting
    - title: 📦 Dependencies
      labels:
        - dependencies
        - deps
    - title: 🔄 CI/CD
      labels:
        - ci
        - cd
        - github-actions
    - title: 🏗️ Build & Infrastructure
      labels:
        - build
        - infrastructure
    - title: Other Changes
      labels:
        - "*"
