exclude: |
  ^proofy-artifacts/|
  \.docx$

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        name: mypy
        args:
          [
            "--install-types",
            "--non-interactive",
            "--config-file",
            "pyproject.toml",
          ]
        files: ^(proofy-commons/proofy/core/(api|client)\.py)$
        additional_dependencies: ["types-requests", "pytest", "pluggy", "httpx"]
