"""Runtime components for test execution context and API."""

from .api import (
    add_attachment,
    add_attributes,
    add_file,
    add_metadata,
    add_run_name,
    add_tag,
    add_tags,
    get_current_run_id,
    get_current_server_id,
    get_current_test_id,
    mark_as_critical,
    mark_as_high,
    mark_as_low,
    mark_as_medium,
    set_description,
    set_name,
    set_run_name,
    set_severity,
    tag_as_integration,
    tag_as_regression,
    tag_as_smoke,
    tag_as_unit,
    upload_file,
)
from .context import (
    SessionContext,
    TestContext,
    get_current_session_context,
    get_current_test_context,
    set_current_session_context,
    set_current_test_context,
)
from .decorators import (
    attributes,
    critical,
    description,
    high,
    integration,
    low,
    marker,
    medium,
    name,
    regression,
    severity,
    smoke,
    tags,
    title,
    unit,
)

__all__ = [
    # Context management
    "TestContext",
    "SessionContext", 
    "get_current_test_context",
    "set_current_test_context",
    "get_current_session_context",
    "set_current_session_context",
    
    # Runtime API
    "set_name",
    "set_description",
    "set_severity",
    "add_metadata",
    "add_attributes", 
    "add_tag",
    "add_tags",
    "add_attachment",
    "add_file",
    "set_run_name",
    "get_current_test_id",
    "get_current_server_id",
    "get_current_run_id",
    "mark_as_critical",
    "mark_as_high",
    "mark_as_medium", 
    "mark_as_low",
    "tag_as_smoke",
    "tag_as_regression",
    "tag_as_integration",
    "tag_as_unit",
    "add_run_name",  # Legacy
    "upload_file",   # Legacy
    
    # Decorators
    "name",
    "title",
    "description", 
    "severity",
    "tags",
    "attributes",
    "marker",
    "critical",
    "high",
    "medium",
    "low",
    "smoke",
    "regression", 
    "integration",
    "unit",
]
